### ISSUE TITLE
PDF not displaying properly on Android 6.0

### ISSUE THREAD

**Issue by ChristianXjf** [voghDev/PdfViewPager#112]
Hi,The problem is shown in the figure below.

file: http://dz.enjoy-reading.cn:8082/file/pdf/skjc_qk/STYB201802/STYB201802003.pdf

![screenshot_2019-01-17-02-04-05](https://user-images.githubusercontent.com/37389428/51291551-797e6100-1a42-11e9-9b42-b8f183b323e7.png)

**Comment by voghDev** [comment]
Hello,

thanks for using PdfViewPager. With this few information, I'm afraid there's not much I can do to help. Can you provide a sample project where you are trying to load the file?

I suggest you to look at the other threads with similar causes to see if any of the given solution works for you.
Antother thing I'd suggest is to try another copy of the same PDF document, because sometimes PdfRenderer crashes with specific PDF files, and does not with others. If your PDF is generated, try to generate another copy or to generate it with another program as source.
