### ISSUE TITLE
Electronic chapter problem

### ISSUE THREAD

**Issue by Yis92** [voghDev/PdfViewPager#116]
How to deal with the electronic seal does not show

**Comment by voghDev** [comment]
Hi,

what do you mean with the electronic seal? Can you provide more information please?

**Comment by Yis92** [comment]
<img width="1431" alt="dianzizhang" src="https://user-images.githubusercontent.com/13741732/53075400-0461e800-3528-11e9-80f5-57c0eb7a2b5f.png">

Hi,

Does that make sense? The names are in red. The electronic signature.

thanks.

**Comment by Yis92** [comment]
<img width="1265" alt="dianzizhang" src="https://user-images.githubusercontent.com/13741732/53075700-c618f880-3528-11e9-9e09-38ed2c1b4851.png">


Hi,

The names are in red. The electronic signature.

The circled part does not show.

Does that make sense? 

thanks.

**Comment by zengsuwa** [comment]
![image](https://user-images.githubusercontent.com/19630479/53075538-63276180-3528-11e9-92a8-0755ce53266d.png)

![qq 20190220160109](https://user-images.githubusercontent.com/19630479/53075716-d335e780-3528-11e9-9f3e-4d00212dc38c.png)
PDF's electronic signature disappeared.

**Comment by voghDev** [comment]
Ok. I see.

This issue is similar to #29. There are certain items that seems not to display when loading a page in a `PdfRenderer`. I suggest that if you need a more advanced rendering of the PDF document, you should try a more specific SDK like [PSPDFKit](https://pspdfkit.com/). `PdfRenderer` is a very basic widget and its features are limited.
