### ISSUE TITLE
Make RemotePDFActivity zoombale

### ISSUE THREAD

**Issue by venkateshj99** [voghDev/PdfViewPager#32]
Hi, I was looking for PDF parser project, like download from API without save in SD/anywhere and found RemotePDFActivity, its simple to implement.. I have tried to set Zoom effect in 'RemotePDFActivity' but cant do it as expected..Can you help me on this..It will be helpful for others too..

**Comment by voghDev** [comment]
Hi,

I guess that your intention is to download and render a PDF document without storing it on SD card. I don't know if there is an approach for this, but its not one of the purposes of the library.

In order to have zooming capability, you can implement a manual download, then use regular `PdfViewPager` once the file has been downloaded. 

You can use a temporary file that you can delete after the rendering, if that suits your needs.

**Comment by voghDev** [comment]
Have you made any progress on this? Did the remote download suit you?
