### ISSUE TITLE
java.lang.OutOfMemoryError:  at es.voghdev.pdfviewpager.library.adapter.SimpleBitmapPool.createBitmapAtIndex (SimpleBitmapPool.java:83)

### ISSUE THREAD

**Issue by Gaurav2621998** [voghDev/PdfViewPager#98]
This error is coming on nearly all versions of Android, And I don't get the why this error will come. So Please Help me out.And give solution to remove this error.
Thank you..

**Comment by voghDev** [comment]
What's the size of the PDF you are trying to load? If it crashes in all Android devices, probably your PDF file is the cause

**Comment by Gaurav2621998** [comment]
size of pdf is 4 to 5 mb. Yes it will crashes on all android devices

**Comment by voghDev** [comment]
Have you tried another PDF such as the one in the example project?

**Comment by Gaurav2621998** [comment]
sometime it will working and sometime it will give error..?

**Comment by voghDev** [comment]
Your App is definitely getting out of memory. Probably you have many resources loaded into memory, and when you try to load the Pdf renderer, it overflows. Sometimes it does not crash probably because you have navigated through the app for just a few time, and memory is still not overloaded. I've seen a similar situation recently with a heavy PDF document. I suggest to create your own subclass of BasePdfPagerAdapter and try to render the PDF document using less memory
